### ISSUE TITLE
How do I adjust linter settings?

### ISSUE THREAD

**Issue by MicahZoltu** [microsoft/vscode-azure-blockchain-ethereum#1]
i am getting squigglies for something that I want to ignore and isn't an error, just a style guideline I disagree with.  How can I turn off one of the linter settings when editing a Solidity file?

**Comment by caleteeter** [comment]
The extension had a dependency on the [Solidity ](https://marketplace.visualstudio.com/items?itemName=JuanBlanco.solidity) extension.  You can configure the linter there in the user settings.  If you check out the linting section [here](https://marketplace.visualstudio.com/items?itemName=JuanBlanco.solidity) you can see these settings.
