### ISSUE TITLE
Can we add a mention to the Azure Blockchain Developer Container in the docs?

### ISSUE THREAD

**Issue by cmendible** [microsoft/vscode-azure-blockchain-ethereum#10]
Hi, 

I think we can add a reference to the [Azure Blockchain](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/azure-blockchain) developer container in the docs.

If you find the idea interesting I could create a PR with the requiered changes.

Thoughts?

**Comment by caleteeter** [comment]
This looks super cool, let me run through this as well and will update the thread here then.  Much thanks for putting this together!

**Comment by cmendible** [comment]
Hi @caleteeter any news on this one?

Thanks!

**Comment by caleteeter** [comment]
@cmendible sorry for the delay.  Yes I have tested this and we have one subcomponent that doesn't work in specific scenarios (Smart Contract Interaction).  We are addressing this but I see this published and it works well.  Much thanks!

**Comment by caleteeter** [comment]
All working well!

**Comment by cmendible** [comment]
Was the Developer Container references added to the docs? Can't find the reference...

**Comment by caleteeter** [comment]
Not currently, but will loop in the technical writer here.  Also, we will record some short demos videos as well for blocktalk/youtube.
