### ISSUE TITLE
Cannot read property 'node' of undefined [Mac]

### ISSUE THREAD

**Issue by anshulahuja98** [microsoft/vscode-azure-blockchain-ethereum#11]
While trying to deploy smart contracts to azure, I get the following error in Vs code
Unable to even find any trace logs or debug info anywhere

```
Cannot read property 'node' of undefined
```

![image](https://user-images.githubusercontent.com/36476228/61043303-84afb980-a3f3-11e9-81dd-8a9eb832785c.png)

Need assistance

**Comment by caleteeter** [comment]
HI @anshulahuja98 , sorry to here you hit this issue.  Had a few questions.  I assume you have all the prerequisites installed as you mentioned this was during deployment.  Was this the New Solidity project -> basic project or a truffle box?  Additionally you can find some logs in the output window (under Azure Blockchain Service).  We have an updated version that will published very soon that might address this but hard to say without a bit more info on the project you were deploying.  Also, could you post the truffle-config.js here (remove any key references as well).

**Comment by anshulahuja98** [comment]
Yes I have all the pre requisites installed
The new solidity project was a truffle box project
There are no logs on ABS on the portal

Looking forward to the update!

truffle-config.js
```
module.exports = {
  networks: {
    development: {
      host: "localhost",
      port: 8545,
      network_id: "*", // Match any network id
      gas: 5000000
    }
  },
  compilers: {
    solc: {
      settings: {
        optimizer: {
          enabled: true, // Default: false
          runs: 200      // Default: 200
        },
      }
    }
  }
};

```

Just to confirm, I was not deploying to the local truffle, I was deploying directly to ABS.

**Comment by plakhanpal** [comment]
Hi Caleteeter, is there any update on this issue ? I came across the same issue while using the azure blockchain development kit for etherium vscode extension on windows 10 too. I am using the truffle box code for refrigerated transportation with solc compiler 0.4.23 and truffle 4.1.7.

**Comment by caleteeter** [comment]
Hi @plakhanpal , ok, so I see one issue here being you are on truffle 4.x.  This is likely the culprit here.  Can you please upgrade to the latest truffle version (0.5.28)?

`npm install truffle -g`

Looks like our prereq checks are not highlighting this issue (4.x).

After you install the new truffle you can set the compiler in the truffle config to use the old solc version (0.4.x).  https://www.trufflesuite.com/docs/truffle/reference/configuration#compiler-configuration

Let me know if you have any issues with this.

**Comment by caleteeter** [comment]
Closing for now, please reopen if issue remains.
