### ISSUE TITLE
Is it possible to have python 3

### ISSUE THREAD

**Issue by rustedwizard** [microsoft/vscode-azure-blockchain-ethereum#13]
Hi:

By my knowledge the Python 2 will be out of support quiet soon, so, I am just wondering if this extension can work with Python 3? I don't think depends on a out of support software would be a very good idea.

**Comment by caleteeter** [comment]
Agreed @rustedwizard .  To be transparent, the dependency on python v2.x is from a npm package for encryption that we have a dependency with.  We are actively working on cleaning up this dependency to remove the need for python all together.

**Comment by caleteeter** [comment]
@rustedwizard We are close to having the dependency for python removed!

**Comment by caleteeter** [comment]
So we have been hard at work on this.  For native installs, some packages we are dependent on are the sticking point here.  Sorry for the extreme lag here but takes more time to untangle the dependency tree.  :)

**Comment by keyz182** [comment]
@caleteeter Any work on this? What is the dependency that's requiring Py2?

**Comment by caleteeter** [comment]
@keyz182 the dependency is deep rooted, so our extension depends on some truffle packages (for instance the hdwallet-provider).  Inside this has a dependency on keccak.  This package, requires a "build" when installing.  This build requires Python.  :(

**Comment by keyz182** [comment]
I see - Truffle has a transitive dependency on https://github.com/ethereumjs/merkle-patricia-tree, which depends on an older version of https://github.com/ethereumjs/ethereumjs-util/, which in turn has a transitive dependency to an old version of Keccak that doesn't use the latest node-gyp (which supports py3).

The Markle-patricia-tree does have up-to-date deps in master, but they're unreleased. So the fix requires a new markle-patricia-tree lib update, and then updates of all the libs in between (one of which seems to be ethereumjs-block which is now archived on github?).

Yeah, that's a mess!

**Comment by caleteeter** [comment]
I am closing this for now, no short term fix here, but something we look to improve in the future.  We have to, we can't run on python 2.x FOREVER! :)
