### ISSUE TITLE
Can't run Ganache server

### ISSUE THREAD

**Issue by EuLeEr** [microsoft/vscode-azure-blockchain-ethereum#14]
This message after command "Connect to Consortium"->"Connect to local Ganache network"->"Enter local port number"
 
![Bug](https://user-images.githubusercontent.com/1876361/62660617-34d2fc80-b977-11e9-9f23-cb1dfa2e29f8.PNG)

from command line ganache-cli working right on default port 8545

**Comment by caleteeter** [comment]
Thanks for the feedback @EuLeEr .  We are investigating this, might be a timing issue or possibly a port blocking issue.  To clarify, if you start ganache-cli from command line then deploy there from the extension, everything works fine?  Note in this case you would not need to explicitly connect to this consortium.

**Comment by caleteeter** [comment]
Hi @EuLeEr, checking back in here.  I did some investigation.  We have a bug we are tracking down for ganache-cli server to continue to run after vscode ide shutdown.

Wondering one thing that you can check.  Kill the ganache process first (if one is running).

`Stop-Process -Id (Get-NetTCPConnection -LocalPort 8545).OwningProcess -Force`

After this when you start vscode with this extension installed, and create a new Solidity project -> Basic Project, then right click Compile, then right click Deploy, and select the development option.  This will start ganache automatically and deploy.

Can you confirm this works for you?

**Comment by EuLeEr** [comment]
Thanks for investigating, @caleteeter  !
But after 10 minutes creating this issue appeared another error 
![image](https://user-images.githubusercontent.com/1876361/63379848-d73ea700-c39d-11e9-860b-385b529602ef.png).

I reinstall extension, now update VSCode  to release 1.37.1 , bur error repeating . Version OS Windows 10 Pro 1803.

Now I make "new Solidity project " and is only what I can made :-(

**Comment by caleteeter** [comment]
Ok @EuLeEr , so to back up a bit.  With you clean install now, you can start the extension, create a new solidity project and this will create the project structure (and install the HD wallet).  Sounds like this is working ok for you.

After that when you deploy locally, which will start ganache, you get this hang.   I have a thought here but want to prove this out myself on on 1803 build to be sure this works ok.  Gimme a bit here will post you back some results / possible resolution.

**Comment by EuLeEr** [comment]
Sorry , I was confused you.
Now :
1. I run "new Solidity porject"
2 after 10-15 second from that I got errors from above comment ("command 'truffle ...
3 After 3 minutes "... crashed 5  times in the last 3 minutes"
4. Execution finished

and is only what I can made :-(.
PS. I was tried reinstall VSCode. After new install all Extension recovered , and error also

**Comment by EuLeEr** [comment]
Solution:

1. Close VS Code
2. Delete %userprofile%/.vscode
3. Run VS Code
4. Again add extension

**Comment by caleteeter** [comment]
I had a hard time repro'ing this so thanks so much for taking the time to add the details here.   This appears to be some cached data issue.  We will log this in our FAQ for sure.
