### ISSUE TITLE
Node and Python not identified in PATH

### ISSUE THREAD

**Issue by snario** [microsoft/vscode-azure-blockchain-ethereum#17]
<img width="1304" alt="Screen Shot 2019-08-28 at 13 20 01" src="https://user-images.githubusercontent.com/1933029/63877948-9397fe80-c996-11e9-9393-16329cddffa5.png">

**Comment by caleteeter** [comment]
hi @snario , for Python, we need at least 2.7.15 (10 will not do).  For node we check for 10.15.0 or greater, so looks like you have 10.15.3.  This one seems a bit odd.

Can you provide the following so we can troubleshoot?

OS Version
NPM Version
VS Code Version

Thanks!!

**Comment by snario** [comment]
Updated Python to 2.7.16 at `/usr/local/bin/python` and see the same issue.

MacOS 10.14.6
npm@6.4.1 (located at /usr/local/Cellar/nvm/0.34.0/versions/node/v10.15.3/bin/npm)
VS Code Version: 1.37.1

**Comment by caleteeter** [comment]
Thanks @snario checking this but likely a bug in our dependency checking.

**Comment by caleteeter** [comment]
@snario , any chance you can check this with your configuration with our latest build 0.1.9.  Its working fine on our tests.

**Comment by michelpf** [comment]
Same here.
Using VSCode in MacOS.

![image](https://user-images.githubusercontent.com/8541053/68233846-c554c380-ffde-11e9-8c87-71599bc846ad.png)

**Comment by michelpf** [comment]
Same here.
Using VSCode in MacOS.

![image](https://user-images.githubusercontent.com/8541053/68233846-c554c380-ffde-11e9-8c87-71599bc846ad.png)

**Comment by caleteeter** [comment]
@michelpf we have made some changes with 0.1.12 and with 0.1.3 (coming in a few days) that I believe should address this.  Also with nodejs moving to 12.14.0 as LTS, wondering if you have made the move to 12.x.  We have been testing wtih MacOS as well with no issues, but interested if there is breakage here, where the diff is.

**Comment by caleteeter** [comment]
This is resolved in the latest versions.  Please feel free to reopen if you experience this same issue.
