### ISSUE TITLE
[Execute command] ReferenceError: HDWalletProvider is not defined

### ISSUE THREAD

**Issue by filzatariq** [microsoft/vscode-azure-blockchain-ethereum#18]
I am getting this error "Failed to run command - npx truffle migrate --reset --network filzablockchain. More details in output" when I try to deploy my Dapp on ABS following the given instructions. In output I get this major error:  [Execute command] ReferenceError: HDWalletProvider is not defined.

![image](https://user-images.githubusercontent.com/36457264/64123961-313c6500-cdbf-11e9-96cf-b96a54fd8a4f.png)

Here is my full Dapp Link: https://github.com/filzatariq/decentralized-newsfeed

The Dapp is created using Truffle Petshop Box : https://github.com/truffle-box/pet-shop-box

**Comment by caleteeter** [comment]
Apologies on the delay getting back to you @filzatariq .  I understand your issue, when using a truffle box (other than the basic project).  We have been thinking about this a bit.  It seemed a bit heavy for us to modify the configuration of a box that was created by others.  The proposed approach we have been thinking about is to prompt you when the wallet is not installed, and allow you to install.

In the interium, you can add the following to your truffle-config.js.

const HDWalletProvider = require('truffle-hdwallet-provider');
const fs = require('fs');

Then run `npm install truffle-hdwallet-provider@1.0.10`

**Comment by caleteeter** [comment]
@filzatariq , not sure if you have been following but we added this feature to allow users to optionally install the wallet when its not install, for public truffle boxes!!  Also you can deploy to Azure Blockchain Service with this as well!!
