### ISSUE TITLE
Show Smart Contract Interaction Page does not work on VScode

### ISSUE THREAD

**Issue by charlie4biz** [microsoft/vscode-azure-blockchain-ethereum#19]
Hello, this feature "Show smart contract interaction page" after deployment to local network does not work. Tried it several times and just get a blank page but if I try it on the HelloBlockchain.sol contract, it works.

Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

    pragma solidity ^0.5.0;

    contract Context {
    constructor () internal { }

    function _msgSender() internal view returns (address) {
        return msg.sender;
    }

    function _msgData() internal view returns (bytes memory) {
        this; 
        return msg.data;
    }
    }

    interface IERC20 {

    function totalSupply() external view returns (uint256);

    function balanceOf(address account) external view returns (uint256);

     function transfer(address recipient, uint256 amount) external returns (bool);

    function allowance(address owner, address spender) external view returns (uint256);

    function approve(address spender, uint256 amount) external returns (bool);

    function transferFrom(address sender, address recipient, uint256 amount) external returns (bool);

    event Transfer(address indexed from, address indexed to, uint256 value);

    event Approval(address indexed owner, address indexed spender, uint256 value);
    }

    library SafeMath {

    function add(uint256 a, uint256 b) internal pure returns (uint256) {
        uint256 c = a + b;
        require(c >= a, "SafeMath: addition overflow");

        return c;
    }

    function sub(uint256 a, uint256 b) internal pure returns (uint256) {
        return sub(a, b, "SafeMath: subtraction overflow");
    }

    function sub(uint256 a, uint256 b, string memory errorMessage) internal pure returns (uint256) {
        require(b <= a, errorMessage);
        uint256 c = a - b;

        return c;
    }

    function mul(uint256 a, uint256 b) internal pure returns (uint256) {
        // Gas optimization: this is cheaper than requiring 'a' not being zero, but the
        // benefit is lost if 'b' is also tested.
        // See: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/522
        if (a == 0) {
            return 0;
        }

        uint256 c = a * b;
        require(c / a == b, "SafeMath: multiplication overflow");

        return c;
    }

    function div(uint256 a, uint256 b) internal pure returns (uint256) {
        return div(a, b, "SafeMath: division by zero");
    }

    function div(uint256 a, uint256 b, string memory errorMessage) internal pure returns (uint256) {
        // Solidity only automatically asserts when dividing by 0
        require(b > 0, errorMessage);
        uint256 c = a / b;
        // assert(a == b * c + a % b); // There is no case in which this doesn't hold

        return c;
    }

    function mod(uint256 a, uint256 b) internal pure returns (uint256) {
        return mod(a, b, "SafeMath: modulo by zero");
    }

    function mod(uint256 a, uint256 b, string memory errorMessage) internal pure returns (uint256) {
        require(b != 0, errorMessage);
        return a % b;
    }
    }

    contract tokens is Context, IERC20 {
    using SafeMath for uint256;
    mapping (address => uint256) private _balances;
    mapping (address => mapping (address => uint256)) private _allowances;
    uint256 private _totalSupply;

    function totalSupply() public view returns (uint256) {
        return _totalSupply;
    }

    function balanceOf(address account) public view returns (uint256) {
        return _balances[account];
    }

    function transfer(address recipient, uint256 amount) public returns (bool) {
        _transfer(_msgSender(), recipient, amount);
        return true;
    }

    function allowance(address owner, address spender) public view returns (uint256) {
        return _allowances[owner][spender];
    }

    function approve(address spender, uint256 amount) public returns (bool) {
        _approve(_msgSender(), spender, amount);
        return true;
    }

    function transferFrom(address sender, address recipient, uint256 amount) public returns (bool) {
        _transfer(sender, recipient, amount);
        _approve(sender, _msgSender(), _allowances[sender][_msgSender()].sub(amount, "ERC20: transfer amount exceeds allowance"));
        return true;
    }

    function increaseAllowance(address spender, uint256 addedValue) public returns (bool) {
        _approve(_msgSender(), spender, _allowances[_msgSender()][spender].add(addedValue));
        return true;
    }

    function decreaseAllowance(address spender, uint256 subtractedValue) public returns (bool) {
        _approve(_msgSender(), spender, _allowances[_msgSender()][spender].sub(subtractedValue, "ERC20: decreased allowance below zero"));
        return true;
    }

    function _transfer(address sender, address recipient, uint256 amount) internal {
        require(sender != address(0), "ERC20: transfer from the zero address");
        require(recipient != address(0), "ERC20: transfer to the zero address");
        _balances[sender] = _balances[sender].sub(amount, "ERC20: transfer amount exceeds balance");
        _balances[recipient] = _balances[recipient].add(amount);
        emit Transfer(sender, recipient, amount);
    }

    // function verifySchedule(uint scheduleid) internal view returns (uint) {
    //     uint amount = validateSchedule(scheduleid);
    //     return amount;
    //  }

    // function _mint(uint256 amount) internal returns(bool) {
    //     require(owner() == msg.sender, "ERC20: mint to the zero address");
    //    address _account = owner();
    //     _totalSupply = _totalSupply.add(amount);
    //     _balances[_account] = _balances[_account].add(amount);
    //     return true;
    // }

    // function generateToken(uint scheduleid) public returns(bool) {
    //     require(owner() == msg.sender, "ERC20: mint to the zero address");
    //     //if token verifySchedule come back true
    //    uint256 amount = verifySchedule(scheduleid);
    //     if(_mint(amount))
    //     updateSchedule(scheduleid, true);
    //     return true;
    // }

    function _approve(address owner, address spender, uint256 amount) internal {
        require(owner != address(0), "ERC20: approve from the zero address");
        require(spender != address(0), "ERC20: approve to the zero address");

        _allowances[owner][spender] = amount;
        emit Approval(owner, spender, amount);
    }

   }

**Comment by caleteeter** [comment]
Let me check with this contract could be a bug with the parsing and rendering of dynamic contract UI.  Thanks for confirming it works with the default _hello world_ contract.

**Comment by charlie4biz** [comment]
@caleteeter ok. thanks. Also, I would like to know if it is possible for VSCode to "generate the microservices for smart contracts" in javascript instead of C#.

**Comment by charlie4biz** [comment]
hello, sorry I don't know where to post this so have to come here to do so. During provisioning of the blockchain service, where is the private key and account stored as that was not sent to us? A department in our organization is in charge of provisioning resources but they said they didn't see any key(public and private). Would be nice for it to be sent via email during provisioning. I was able to get the details via the mnenomic key generated from vscode when connecting it to the blockchain service.

**Comment by caleteeter** [comment]
For the question about generating microservices for js in addition to C#, I will add this to our backlog.

**Comment by caleteeter** [comment]
@charlie4biz For the Azure Service, when you provision the service, the first node of the member will have an account created by default.  So for logic apps, there are 2 ways to setup for Ethereum connection:

1.  Get the account address from the main blade for your Azure Blockchain Service.
2.  Use the password used when provisioning the member.

This will use the account from the first node.

You can also use the VS Code extension, which uses truffle-hdwallet-provider, and will create accounts to be used as well.  As you stated you can get the private key (using the Command Palette command).

**Comment by michelpf** [comment]
Sorry, but you were able to open the Interaction Page?
In my case, even using the HelloWorld, I can't use the interaction page.

I can do the interaction using the Logic Apps with no problems.

![image](https://user-images.githubusercontent.com/8541053/68496154-70a88700-0230-11ea-93f7-8cd711d90912.png)

**Comment by cnsegura** [comment]
Hi Michel - are you still having problems with the contract interaction page? You must deploy this locally first, before trying to open it up. Did it deploy Ok?

**Comment by michelpf** [comment]
Sorry, you were right.
It worked, and enjoyed it a lot! Nice work with this extension!
