### ISSUE TITLE
Unfinished FAQ

### ISSUE THREAD

**Issue by only4sim** [microsoft/vscode-azure-blockchain-ethereum#2]
The first FAQ seems to be unfinished. It is like this：

> Q: I installed all of the pre-requisite software, but I still get the "missing" or "old version" notification for Python
> A: It's pretty likely that Python was installed without being added to your system PATH variable (the default installation mode of Python). To resolve this problem, you need to add your Python directory to the system path. You may do this in a

**Comment by caleteeter** [comment]
Sorry about that @only4sim we will the FAQ updated.  The guidance will be for both Mac and Windows, which will differ in how the PATH var is set, but same result.  Wanted to make sure you were unblocked, while we get this updated, so let me know if you are stuck.

**Comment by only4sim** [comment]
Thanks, @caleteeter. I am using the Windows system now, so it is not very difficult to solve.

**Comment by cnsegura** [comment]
FAQ updated for Windows. Future updates for setting PATH variable in OSX, Linux planned
