### ISSUE TITLE
Question - how to use custom ETH network?

### ISSUE THREAD

**Issue by zulhfreelancer** [microsoft/vscode-azure-blockchain-ethereum#20]
Hi,

From the docs, I saw `Azure Blockchain: Create a new network`. How do I connect to non-Azure Blockchain node i.e. Ganache or Goerli testnet (via Infura)?

Thank you.

**Comment by caleteeter** [comment]
For local network, you can create a network that will prompt you for a name and port.  The extension will then create a ganache instance for you in the background, then just right click on the contract, deploy and use this new network.

For Infura, you can create a new project in Infura or connect to an existing one.  We are modifying the login to Infura but for now you will need to bring up the Command Palette and chose Azure Blockchain: Sign into Infura account.  This will then prompt you for credentials for Infura, when you return after logging in, you can then connect or create a new project.  Then the same model of right click on contract and deploy, choosing the appropriate endpoint (mainnet, ropsten, etc.).

`NOTE: We don't hit a faucet for Infura so you will need to fund the account for testnet or real eth account for mainnet to use.`

**Comment by zulhfreelancer** [comment]
Thank you @caleteeter. How to connect to non-Infura Geth/Parity node?

**Comment by caleteeter** [comment]
@zulhfreelancer that is manual for now, you can update the truffle configuration manually to add your node there.

**Comment by caleteeter** [comment]
@zulhfreelancer  we have added specific integration to Infura (in version 0.1.9 and greater).  This makes using pulblic nodes much easier!
