### ISSUE TITLE
Block explorer in Azure console

### ISSUE THREAD

**Issue by michelpf** [microsoft/vscode-azure-blockchain-ethereum#22]
In some youtube videos of the Microsoft Developer, has a different view of console in Blockchain Services (https://www.youtube.com/watch?v=yZQ9a22q82E).

It is an interesting view showing the blocks, tps and block count.

![image](https://user-images.githubusercontent.com/8541053/68494038-756b3c00-022c-11ea-8e3c-d5bf2bcb118f.png)

But, in my actual view, there is no such data.

![image](https://user-images.githubusercontent.com/8541053/68494272-e6125880-022c-11ea-9722-fb576fc3973d.png)

I need to do something in order to view that block explorer?

**Comment by caleteeter** [comment]
@michelpf sorry for the lag getting back to you.  The screenshots in the video were some earlier preview builds of Azure Blockchain Service, so the one in the lower screen is what rolled out (and is the current build).  Its good feedback we can relay to the ABS team for consideration.  

Also, one of our strategic partners, web3labs, has a great blog post on how to connect their block explorer to an ABS instance -> https://medium.com/web3labs/azure-blockchain-service-explorer-495e6702d762
