### ISSUE TITLE
Token Generation does not work.

### ISSUE THREAD

**Issue by mjtpena** [microsoft/vscode-azure-blockchain-ethereum#24]
I was trying to generate a token using the token generation capability of the extension.
However, when I tried to click on Generate, nothing happens.

I'm using Windows. VS Code stable edition.

![TokenGeneration](https://user-images.githubusercontent.com/19221213/70133883-17226380-16db-11ea-9628-49deae2d23ad.PNG)

**Comment by cnsegura** [comment]
Hi mjtpena - the token feature is not yet released, only the visual items you posted have been implemented. Sorry for the confusion, we will update the FAQ to make it clear it is not yet functional.
