### ISSUE TITLE
Generate Azure Function Microservices displays "Generated the logic app"

### ISSUE THREAD

**Issue by mjtpena** [microsoft/vscode-azure-blockchain-ethereum#25]
![image](https://user-images.githubusercontent.com/19221213/70701888-42cbcc00-1d21-11ea-997b-9e1cd757b10b.png)
It should obviously be " azure functions"

**Comment by caleteeter** [comment]
Thanks for this @mjtpena , will get this resolved in the next release!

**Comment by caleteeter** [comment]
@mjtpena we have resolved this in the latest release (v0.1.13), enjoy!
