### ISSUE TITLE
'Build Contracts' is not building to the build folder on an existing project and therefore I am unable to debug, or use smart contract interaction page. 

### ISSUE THREAD

**Issue by mcplums** [microsoft/vscode-azure-blockchain-ethereum#26]
Build Contracts is instead building to app/src/contracts which is the default directory for compiled files in my truffle project. Contracts SHOULD build here, so the plugin is building correctly. 

However, it seems that the Smart Contract Interaction page, looks for things in the build folder. 

I have tried manually copying over the json files from app/src/contracts to build/ but it this just caused the program to crash. 

Specifically, when I try and select 'show smart contract interaction page' I get the error "Contract not deployed yet" even though I just deployed it previously with zero errors. 

Curiously, I note that when I click 'deploy contracts' from the above error message, I am greeted with "Compiled contract is missing for solidity file.". I do NOT get this message when I deploy via the command palette. 

I am also having issues debugging- I get the error "No compiled contracts found in /repo/build/contracts"

Wat do?

**Comment by caleteeter** [comment]
@mcplums Just to clarify, in your project are you redirecting the build to another folder (via truffle config or symbolic link)?  I believe this might be the issue as we have a hard dependency on the build folder structure currently, but that could be updated to add flexibility of build output.

**Comment by mcplums** [comment]
It turns out, I am :) not knowingly, my project is a fork of another project that has this line in truffle_config:

`contracts_build_directory: path.join(__dirname, "app/src/contracts")`

However, as mentioned, it still doesn't work if I manually copy stuff over to /build, should it?

**Comment by gnidan** [comment]
> However, as mentioned, it still doesn't work if I manually copy stuff over to /build, should it?

Just to confirm, are you copying the JSON files to `build/contracts/`? That's the default location Truffle uses.

**Comment by caleteeter** [comment]
We have a fix for this in the 0.1.13 release, targeting end of this week!  We have support for all the redirectors there (contracts, build, migrations)!

**Comment by caleteeter** [comment]
@mcplums  Fixed in version 0.1.13 (latest).  `NOTE: this update will allow the redirection of contracts_build_directory, however we are still adding support for contracts_directory (source) and contracts_migration_directory (migration scripts), which will come in a future release.
