### ISSUE TITLE
Support read functions taking parameters in Smart Contract Interaction

### ISSUE THREAD

**Issue by abcoathup** [microsoft/vscode-azure-blockchain-ethereum#38]
Firstly: the Smart Contract Interaction page is fantastic.

Currently read functions that take parameters such as `balanceOf` and `allowance` in an ERC20 token are not supported in Smart Contract Interaction and show `Sorry! Complex structures has not supported yet!`

<img width="599" alt="Smart Contract Interaction read functions with parameters" src="https://user-images.githubusercontent.com/28278242/82015105-56f56a00-96c1-11ea-853c-92cccea95287.png">

## SimpleToken.sol
Simple ERC20 token example
```
pragma solidity ^0.5.0;

import "./openZeppelin/token/ERC20/ERC20.sol";
import "./openZeppelin/token/ERC20/ERC20Detailed.sol";


/**
 * @title SimpleToken
 * @dev Very simple ERC20 Token example, where all tokens are pre-assigned to the creator.
 * Note they can later distribute these tokens as they wish using `transfer` and other
 * `ERC20` functions.
 */
contract SimpleToken is ERC20, ERC20Detailed {
    /**
     * @dev Constructor that gives msg.sender all of existing tokens.
     */
    constructor() public ERC20Detailed("SimpleToken", "SIM", 18) {
        _mint(msg.sender, 10000 * (10**uint256(decimals())));
    }
}
```

**Comment by caleteeter** [comment]
Yes, @abcoathup appreciate the comments here.  To be honest we weren't even sure that users would use this, so we put this out there with some minimal support for types.  I have heard from others that they like this feature as well, so I will add this to the backlog to add support for complex types as well as properties for state variables (public).

**Comment by caleteeter** [comment]
I am closing this for now.  Enhancing the smart contract interaction is on our radar and something we will be looking to expand going forward.
