### ISSUE TITLE
Open Zeppelin: Version - Setting has an invalid type, expected "string". Fix in JSON

### ISSUE THREAD

**Issue by abcoathup** [microsoft/vscode-azure-blockchain-ethereum#41]
When using OpenZeppelin Contracts, plugin settings shows error: `Setting has an invalid type, expected "string". Fix in JSON`

<img width="470" alt="Setting has an invalid type" src="https://user-images.githubusercontent.com/28278242/82017576-cae64100-96c6-11ea-8437-44530cbbf1ec.png">

Setting to the default version still shows the error
```
{
    "azureBlockchainService.openZeppelin.version": "2.5.0"
}
```

**Comment by caleteeter** [comment]
Yes, I am aware of the `Setting has an invalid type, expected "string". Fix in JSON` bug.  I fix is inflight for this.  Note the correct OZ version will be used, but the settings error here needs to be resolved.

**Comment by caleteeter** [comment]
I have seen with the latest VS Code updates, that this is no longer an issue.  I tested this on a fresh machine with retail version of VS Code and with the Insiders branch.  Closing this issue as a result.
