### ISSUE TITLE
Smart Contract UI stuck at ⚙️ Loading dapp...

### ISSUE THREAD

**Issue by krasi-georgiev** [microsoft/vscode-azure-blockchain-ethereum#47]
Created the demo project
created a local network
compiled the contracts
deployed the contracts

right click on `HelloBlockchain.sol` -> Show interaction page -> black page with ⚙️ Loading dapp...

code -v
1.45.1
5763d909d5f12fe19f215cbfdd29a91c0fa9208a
x64

Blockchain Development Kit for Ethereum
1.3.1

logs:

```
Get version for required apps: node,npm,git,python,truffle,ganache-cli
[Execute command] v14.3.0
[Execute command] 6.14.5
[Execute command] git version 2.19.1
[Execute command] Python 2.7.16
[Execute command] blockchain-ethereum-template@0.1.0 /home/krasi/src/github.com/krasi-georgiev/playground
└── truffle@5.1.27  invalid

[Execute command] npm[Execute command]  ERR! invalid: truffle@5.1.27 /home/krasi/src/github.com/krasi-georgiev/playground/node_modules/truffle
[Execute command] blockchain-ethereum-template@0.1.0 /home/krasi/src/github.com/krasi-georgiev/playground
└── (empty)

[Execute command] Ganache CLI v6.9.1 (ganache-core: 2.10.2)
Get version for required apps: truffle
[Execute command] 
Working dir: /home/krasi/src/github.com/krasi-georgiev/playground
Running command
npx truffle compile
[Execute command] 
Compiling your contracts...
[Execute command] ===========================
[Execute command] > Compiling ./contracts/HelloBlockchain.sol
[Execute command] > Compiling ./contracts/Migrations.sol
[Execute command] > Artifacts written to /home/krasi/src/github.com/krasi-georgiev/playground/build/contracts
[Execute command] > Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang

[Execute command] Finished running command
[Execute command] 3635
[Execute command] 3635
Get version for required apps: truffle
[Execute command] 
Working dir: /home/krasi/src/github.com/krasi-georgiev/playground
Running command
npx truffle migrate --reset --network loc_test_test
[Execute command] 
Compiling your contracts...
[Execute command] ===========================
[Execute command] > Everything is up to date, there is nothing to compile.
[Execute command] 
[Execute command] 
[Execute command] 
Starting migrations...
======================
> Network name:    'loc_test_test'
> Network id:      1590594385261
> Block gas limit: 6721975 (0x6691b7)

[Execute command] 
1_initial_migration.js
======================
[Execute command] 
   Replacing 'Migrations'
   ----------------------
[Execute command]    > transaction hash:    0x9da9b8308916e1c1cdd94cd20d521460b9460bc1d28d3cf166b2fd3ec44bd06b
[Execute command] - Blocks: 0            Seconds: 0
[Execute command]    > Blocks: 0            Seconds: 0
[Execute command]    > contract address:    0xF53B102Bb039a8032Be0026d0e8D42a61c527798
   > block number:        13
   > block timestamp:     1590602473
   > account:             0xC6d8D978150a1b020EBb55e56dBf9A3A6785A16c
   > balance:             99.94744078
   > gas used:            225237 (0x36fd5)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00450474 ETH


[Execute command] - Saving migration to chain.
[Execute command]    > Saving migration to chain.
[Execute command]    > Saving artifacts
   -------------------------------------
   > Total cost:          0.00450474 ETH

[Execute command] 
2_deploy_contracts.js
=====================
[Execute command] 
   Replacing 'HelloBlockchain'
   ---------------------------
[Execute command]    > transaction hash:    0xfa16c69430d9a404add5dc2580fe4c57355b002140bad0d89b5ba41cbf3de0c5
[Execute command] - Blocks: 0            Seconds: 0
[Execute command]    > Blocks: 0            Seconds: 0
[Execute command]    > contract address:    0x48365DA825Bb3408D56FC234Eb712f0ec2C5fb99
   > block number:        15
   > block timestamp:     1590602473
   > account:             0xC6d8D978150a1b020EBb55e56dBf9A3A6785A16c
   > balance:             99.93647462
   > gas used:            505945 (0x7b859)
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.0101189 ETH

[Execute command] 
[Execute command] - Saving migration to chain.
[Execute command]    > Saving migration to chain.
[Execute command]    > Saving artifacts
   -------------------------------------
   > Total cost:           0.0101189 ETH


Summary
=======
> Total deployments:   2
> Final cost:          0.01462364 ETH

[Execute command] 
[Execute command] Finished running command
[Azure Blockchain] Deploy succeeded


```

**Comment by caleteeter** [comment]
I am tracking this, as I have randomly seen the interface stuck at Loading Dapp.  I don't have a clear fix, but I can confirm that closing and reopening this does resolve in the cases I have seen.  Also, I am aware that this is broken on the current Insiders build 1.46.0.

I am tracking a bug about failure to load sometimes on initial load.

**Comment by krasi-georgiev** [comment]
In my case closing and reopening doesn't solve it. Could I provide some more details/logs to help troubleshoot?

**Comment by caleteeter** [comment]
Yikes, ok, I just tested on clean Windows 10 (latest build) with latest retail VS Code 1.45.1.  I can "confuse" it by deploying to other networks and get it to break.  But if I do a clean new project, create no networks and deploy to development, it works consistently.  The interaction page will NOT work for contracts deployed to other networks, other than the default development instance.  Even if I deploy the contract to remote networks, then deploy to teh default, it works.

Can you do one thing for me.

1. Create a new project (basic).
2. Right click on HelloBlockchain in the contracts folder and deploy contract. (select development as the target)
3. After deployment completes, right click on HelloBlockchain and Show Smart Contract Interaction.
4.  Wait 4-5 seconds.  If it still stays loading dapp, close this view (tab) and repeat.
5.  Do this maybe 3-4 times.  (if you keep getting loading and no rendering)

I have a feeling the app is not fully starting to render this and maybe this has some dependency on the speed of the machine.

To be clear we have a webview that is rendering a react app that is receiving the contract that triggered the contract interaction.  Its a simple React App using Drizzle under the covers.  I am wondering if we get these random non renders/fail, that we should add some more logging to the output to ensure if something is causing this fail.  We can add that to the backlog to add for next release.

**Comment by krasi-georgiev** [comment]
now for some reason all I am getting it 

> Cannot start ganache server


<details>
<summary>here are the logs

</summary>
Get version for required apps: node,npm,git,python,truffle,ganache-cli
[Execute command] v14.3.0
[Execute command] 6.14.5
[Execute command] git version 2.19.1
[Execute command] Python 2.7.16
[Execute command] blockchain-ethereum-template@0.1.0 /home/krasi/src/github.com/krasi-georgiev/playground/smartContract
└── (empty)

[Execute command] Truffle v5.1.27 (core: 5.1.27)
[Execute command] Solidity v0.5.16 (solc-js)
[Execute command] Node v14.3.0
Web3.js v1.2.1
[Execute command] blockchain-ethereum-template@0.1.0 /home/krasi/src/github.com/krasi-georgiev/playground/smartContract
└── (empty)

[Execute command] Ganache CLI v6.9.1 (ganache-core: 2.10.2)


</details>

**Comment by caleteeter** [comment]
@krasi-georgiev ok, if you choose to deploy to the default location "development" without creating any other networks, during deployment we will start an instance of ganache in the background on port 8545.  So if this is the flow you chose, the instance will be closed when VS Code is closed (more specifically when the extension is deactivated.  So few things you can do if you hit any issues:

* Restart VS Code, which will restart the ganache instance.
* Check to see if you have ganache listening on port 8545. (e.g. netstat -an | grep "8545" on Linux or netstat -an | findstr "8545" on Windows)

If you have created a local network, again VSCode will start ganache with the port you used to create the network in the background.  To restart you can right click on the instance in the tree under the local network instance.

Hope this helps!

**Comment by krasi-georgiev** [comment]
I reinstalled the extension and restarted vscode and nothing changed.

nothing is listening in the 8545 port.

How do I get the output of the command that is returning this error?

**Comment by caleteeter** [comment]
Really sorry you are getting these problem @krasi-georgiev , and thanks for sticking with me to figure out what is going on here.

So if you open the output window (View -> Output), then change the context to Azure Blockchain.  If you don't see Azure Blockchain just open the view (Blockchain Networks) in the lower left corner.  It will take a few seconds to activate the extension and you should see this in the output window:

```
Get version for required apps: node,npm,git,python,truffle,ganache-cli
[Execute command] v12.16.3
[Execute command] 6.14.4
[Execute command] git version 2.26.2.windows.1
[Execute command] Python 2.7.16
[Execute command] blockchain-ethereum-template@0.1.0 c:\Users\caleteet\source\Demo\VsCodeDemo
`-- (empty)

[Execute command] Truffle v5.1.27 (core: 5.1.27)
[Execute command] Solidity v0.5.16 (solc-js)
[Execute command] Node v12.16.3
Web3.js v1.2.1
[Execute command] blockchain-ethereum-template@0.1.0 c:\Users\caleteet\source\Demo\VsCodeDemo
`-- (empty)

[Execute command] Ganache CLI v6.9.1 (ganache-core: 2.10.2)
```

Next create a new project (create in an empty directory).  From Command Palette look for : Blockchain: New Solidity Project and then choose basic project.  This will take a bit to install as it downloads the wallet package from NPM, pulls the default project from a truffle box and configures everything.  Basically you will see the contracts and other folders turn green when they are ready.

Next right click on the `HelloBlockchain.sol` file in the contracts folder and select Deploy contracts and select the development option for the destination.  You should then see this in the output window.  The first line here is the one that checks for the ganache instance listening.

```
[Execute command]   TCP    127.0.0.1:8545         0.0.0.0:0              LISTENING       2840
Get version for required apps: truffle
[Execute command] 
Working dir: c:\Users\caleteet\source\Demo\VsCodeDemo
Running command
npx truffle migrate --reset --network development
[Execute command] 
Compiling your contracts...
[Execute command] ===========================
[Execute command] > Compiling .\contracts\HelloBlockchain.sol
[Execute command] > Compiling .\contracts\Migrations.sol
[Execute command] > Artifacts written to c:\Users\caleteet\source\Demo\VsCodeDemo\build\contracts
[Execute command] > Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang

[Execute command] 
[Execute command] 
Starting migrations...
======================
> Network name:    'development'
``` 

If there is some problem with this starting this from the extension, you can always just start ganache-cli by yourself.

Open a terminal window and type: `ganache-cli`.  You can then deploy to this using the same `development` destination and it will find this local instance.  

This will start ganache on the same default port.  Possibly you can see any errors there that might help as well.

**Comment by krasi-georgiev** [comment]
I tried all sort of combinations and packages installation/reinstallations node versions etc and the whole process with the node packages seems quite fragile. 


I would try to find an easier workflow, but really thanks for your help. Appreciated.

**Comment by krasi-georgiev** [comment]
btw this is what fixed the ganache-cli issue
https://github.com/trufflesuite/ganache-cli/issues/732

**Comment by caleteeter** [comment]
Ah, I see, what we can do is add a check to throw an error if using > 12 nodejs (LTS) to help this issue.

**Comment by caleteeter** [comment]
Real quick, when you run ganache-cli manually with nodejs14, did you get errors?  I can validate this as well.

**Comment by krasi-georgiev** [comment]
yes there was an error exactly the same as the one to the issues I linked
trufflesuite/ganache-cli#732

**Comment by goh-chunlin** [comment]
Currently, with the approach shared by @caleteeter above, 

> Can you do one thing for me.
> 
> 1. Create a new project (basic).
> 2. Right click on HelloBlockchain in the contracts folder and deploy contract. (select development as the target)
> 3. After deployment completes, right click on HelloBlockchain and Show Smart Contract Interaction.
> 4. Wait 4-5 seconds. If it still stays loading dapp, close this view (tab) and repeat.
> 5. Do this maybe 3-4 times. (if you keep getting loading and no rendering)

we still couldn't get the Smart Contract UI to load, as shown in the following screenshot, even with Ganache Server launched successfully. Also, this is a locally deployed contract.

![image](https://user-images.githubusercontent.com/8535306/89033956-8d5e8f00-d36a-11ea-81ba-c64388e4b7c5.png)

Now I think I agree with @caleteeter that we really need to think of supporting the Smart Contract Interaction page in different manner.

**Comment by caleteeter** [comment]
Working on a short term fix here and have some plans to decouple this from the IDE as well to better support.  Thanks @krasi-georgiev

**Comment by davidmurdoch** [comment]
@caleteeter ganache-cli and ganache-core work in Node v14 now: https://github.com/trufflesuite/ganache-cli/releases/tag/v6.12.0

**Comment by caleteeter** [comment]
Great, thanks @davidmurdoch !

**Comment by huwentao1** [comment]
@caleteeter I still have problems using this now. When was this function fixed?
