### ISSUE TITLE
Could not find commands at commandPalette

### ISSUE THREAD

**Issue by only4sim** [microsoft/vscode-azure-blockchain-ethereum#5]
I want to be able to use following commands directly, like 

`
azureBlockchainService.required.installNpm
`

but obviously not in the commandPalette. Could you kindly help me? Thanks a lot!

![image](https://user-images.githubusercontent.com/35210356/57455642-2b65c580-729e-11e9-92d8-826adc0b997f.png)

**Comment by caleteeter** [comment]
Hi @only4sim !  We opted to not show these commands in the palette to keep it a bit cleaner as we have future commands will be adding here. These are more infrastructure type operations like updating core libraries and such.  Actually been thinking about removing these as commands and make them integral to the extension.

**Comment by only4sim** [comment]
Thanks @caleteeter ! So what should I do if I want to check the version of all required apps?

**Comment by caleteeter** [comment]
The tooling will run at activation and pop up the requirements page if needed.  If you have met all the requirements, then it will stay out of your way.  Are you missing a requirement but not getting the requirements page?

**Comment by only4sim** [comment]
Thanks a lot @caleteeter! In fact, I saw the page, but I closed it when I didn't install all the requirements. I can't find it when I expect to use it again. Then I saw the command line output version of requirements when I used other functions, and added missing requirements.

**Comment by caleteeter** [comment]
I will keep this open as a bug, as it seems if you dismiss the requirements the first time its possible it won't be displayed again.  Need to test this a bit more to ensure it shows until all requirements are filled.

**Comment by caleteeter** [comment]
Resolved this in v0.1.4.  Moved from features to utility modules to keep command contributions clean.
