### ISSUE TITLE
Required Versions

### ISSUE THREAD

**Issue by parkskier426** [microsoft/vscode-azure-blockchain-ethereum#51]
When trying to create a new Solidity project, I get the error, "To run command you should install required apps. Please see details on the Requirements Page", indicating that I don't have a required application. I've checked all versions, they are all either at the required version or later. Any idea what's going on here?

Jeffreys-MacBook-Pro:truffle_testing jschmitz$ node --version
v10.15.0
Jeffreys-MacBook-Pro:truffle_testing jschmitz$ npm --version
6.14.5
Jeffreys-MacBook-Pro:truffle_testing jschmitz$ git --version
git version 2.21.1 (Apple Git-122.3)
Jeffreys-MacBook-Pro:truffle_testing jschmitz$ python --version
Python 2.7.16
Jeffreys-MacBook-Pro:truffle_testing jschmitz$ truffle --version
Truffle v5.1.28 - a development framework for Ethereum
Jeffreys-MacBook-Pro:truffle_testing jschmitz$ ganache-cli -v
Ganache CLI v6.1.0 (ganache-core: 2.1.0)

**Comment by caleteeter** [comment]
Hi @parkskier426 , we have a "validation" checker when the extension is activated that should present a UI to you if you have any unmet requirements.  On the requirements page is any of the buttons lit up?  For example:

![image](https://user-images.githubusercontent.com/8452367/83788937-ff18a600-a663-11ea-8ce5-8290e6f5bfea.png)

**Comment by parkskier426** [comment]
@caleteeter Thanks. The button Node is lit, and in the logs I can see that it's reporting node version 8.15.1, which I assume is the issue.

I've verified from the terminal (node --version) that I'm running node 10.15.3, which I set via nvm.  Any idea how this version mismatch is occurring? From what context does the plugin access node?

**Comment by caleteeter** [comment]
hi @parkskier426 , apologies on the lag getting back to you.  The extension simple runs `node --version` and collects the output to validate the version. Is it possible you have multiple versions of node installed with nvm or something?

**Comment by caleteeter** [comment]
Closing this issue for now, feel free to reopen if your issues is persisting.
