### ISSUE TITLE
Deployment fails to Azure Blockchain Service

### ISSUE THREAD

**Issue by rpajunen** [microsoft/vscode-azure-blockchain-ethereum#54]
I'm following the HelloBlockchain examples from https://docs.microsoft.com/en-us/azure/blockchain/service/send-transaction

Deployment of the automatically generated smart contracts fails with the following error message in VS Code:
`Failed to run command - npx truffle migrate --reset --network <mynetwork>. More details in output`

Details in the output say that: `"Migrations" -- method handler crashed.`

**Comment by caleteeter** [comment]
Hi @rpajunen , were you deploying to an ABS instance?  This sounds like maybe there was some network communication issue.

If you open a terminal window, and run `truffle migrate --reset --network <your network id>` do you get a good deployment?

**Comment by davew-msft** [comment]
I have the same problem.  Running truffle migrate gives this error:

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- method handler crashed.

    at /usr/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:364:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.32 (core: 5.1.32)
Node v10.21.0

**Comment by davew-msft** [comment]
note that I get a similar error on windows as well
1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- method handler crashed.

    at C:\Users\dave\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\deployer\src\deployment.js:364:1
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration._deploy (C:\Users\dave\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\migration.js:70:1)
    at Migration._load (C:\Users\dave\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\migration.js:57:1)
    at Migration.run (C:\Users\dave\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\migration.js:167:1)
    at Object.runMigrations (C:\Users\dave\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:148:1)
    at Object.runFrom (C:\Users\dave\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:110:1)
    at Object.runAll (C:\Users\dave\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:114:1)
    at Object.run (C:\Users\dave\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:79:1)
    at runMigrations (C:\Users\dave\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:253:1)
    at C:\Users\dave\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:218:1
Truffle v5.1.29 (core: 5.1.29)
Node v12.16.3

**Comment by caleteeter** [comment]
Ok, I have attached a simple project.  Can you do this to check your machine setup.

1) Extract the files to a new folder.
2) Open that folder in VS Code.
3) Open the terminal window and run the following commands:
 
```
a) truffle dev
b) truffle migrate
```

This the most basic truffle compile/deploy.

[simple-project.zip](https://github.com/microsoft/vscode-azure-blockchain-ethereum/files/4839650/simple-project.zip)

**Comment by davew-msft** [comment]
that seems to work fine.  Following your exact steps I get:

Summary
=======
> Total deployments:   2
> Final cost:          0.00560964 ETH

My error is occuring when I create a new solidity project and then deploy it following the instructions on the welcome page

**Comment by davew-msft** [comment]
however, deploying that project to ABS results in the same failure:  

Running command
npx truffle migrate --reset --network abs_davewconsortium_davewentzel_davewentzel
[Execute command] 
Compiling your contracts...
[Execute command] ===========================
[Execute command] > Compiling .\contracts\Migrations.sol
[Execute command] > Compiling .\contracts\SimpleStorage.sol
[Execute command] > Artifacts written to c:\Users\dave\Downloads\simple-project\build\contracts
[Execute command] > Compiled successfully using:
   - solc: 0.5.16+commit.9c3226ce.Emscripten.clang

[Execute command] 
[Execute command] 
Starting migrations...
======================
> Network name:    'abs_davewconsortium_davewentzel_davewentzel'
> Network id:      1478
> Block gas limit: 700000000 (0x29b92700)

[Execute command] 
1_initial_migration.js
======================
[Execute command] 
   Deploying 'Migrations'
   ----------------------
[Execute command] 
[Execute command] Error:  *** Deployment Failed ***

"Migrations" -- method handler crashed.

    at C:\Users\dave\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\deployer\src\deployment.js:364:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
[Execute command] Truffle v5.1.32 (core: 5.1.32)
[Execute command] Node v10.15.3
[Execute command] Finished running command
[Azure Blockchain] Deploy failed

**Comment by davew-msft** [comment]
@caleteeter :  just wanted to say upfront, thanks for the quick responsiveness.  Using your basic contract and vscode I can deploy to the local dev network.  I still can't publish to ABS, getting the code above.  Note that I get this on 3 different machines, 2 windows and 1 ubuntu/xfce4.  Does that info help at all?  I quickly created a new ABS instance and was able to connect from vscode and the "BLOCKCHAIN NETWORKS" item under explorer.  I then did a right click on the sol file and deploy, that added the entry to truffle-config.js just fine but again the failure.  I then ran truffle migrate --reset --network abs_davewconsortium_davewentzel_davewentzel and it still fails.  Again, this is on 3 machines and 2 different OSs.  Quite odd.  Any ideas?

**Comment by caleteeter** [comment]
Yikes, let me try a repro here, with a fresh ABS instance and get back to you.

**Comment by caleteeter** [comment]
I am able to duplicate with new instances of ABS, but old ones work fine.  Tracking down this issue, thanks for the heads up.

**Comment by caleteeter** [comment]
@rpajunen @davew-msft Ok, I figured out the issue, we made some changes to gas in the ABS instances.  So as a quick fix you can remote `gas: 0` from your truffle-config.js and the deployments to ABS will complete successfully.  I am updating the core basic project template to ensure this setting is removed.  I should have this pushed by tomorrow.

**Comment by CassieJie** [comment]
Sorry. I have tried to set `gas:0` in truffle-config.js but still encountering errors as follows when I deploy a contract to the ABS. However, the deployment succeeds when I deploy the contract to the localhost.

```
> Network name:    'abs_chariorg_charimeber_charimer'
> Network id:      1493
> Block gas limit: 700000000 (0x29b92700)

[Execute command] 
1_initial_migration.js
======================
[Execute command] 
   Deploying 'Migrations'
   ----------------------
[Execute command] 
[Execute command] Error:  *** Deployment Failed ***

"Migrations" -- method handler crashed.

    at C:\Users\15972\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\deployer\src\deployment.js:364:1
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at Migration._deploy (C:\Users\15972\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\migration.js:70:1)
    at Migration._load (C:\Users\15972\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\migration.js:57:1)
    at Migration.run (C:\Users\15972\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\migration.js:167:1)
    at Object.runMigrations (C:\Users\15972\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:148:1)
    at Object.runFrom (C:\Users\15972\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:110:1)
    at Object.runAll (C:\Users\15972\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:114:1)
    at Object.run (C:\Users\15972\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\migrate\index.js:79:1)
    at runMigrations (C:\Users\15972\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:253:1)
    at C:\Users\15972\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:218:1
[Execute command] Truffle v5.1.31 (core: 5.1.31)
[Execute command] Node v12.15.0
[Execute command] Finished running command
[Azure Blockchain] Deploy failed
```

**Comment by richross** [comment]
I was able to follow @caleteeter 's suggestion of removing 'gas' line from my configuration and this did allow me to deploy to Azure Blockchain.

`[Execute command] 
Summary
=======
> Total deployments:   2
> Final cost:          0 ETH

[Execute command] 
[Execute command] Finished running command
[Azure Blockchain] Deploy succeeded`

**Comment by ShockwaverReal** [comment]
Yep (thou you need to keep the gasPrice to 0)...
Alternatively, set the gas to non 0, and lower than maximum.
In both cases i confirm
`Summary
=======
> Total deployments:   2
> Final cost:          0 ETH

[Execute command] 
[Execute command] Finished running command
[Azure Blockchain] Deploy succeeded`

**Comment by CassieJie** [comment]
Yeah, thanks,  it truly works and I got some outputs in OUTPUT windows(e.g. it list a specific transaction hash....). But I can't see any data in ABS's monitor graphs. I'm wondering whether operations in VScode truly initiate transactions and blocks in ABS? 
```
[Execute command] 
2_deploy_contracts.js
=====================
[Execute command] 
   Replacing 'HelloBlockchain'
   ---------------------------
[Execute command]    > transaction hash:    0xd4104ffa479265e5f40809f6481a66ae18fdb7f3c369a18ad8e91f007125e5e6
[Execute command] - Blocks: 0            Seconds: 0
[Execute command]    > Blocks: 1            Seconds: 6
[Execute command]    > contract address:    0x1aC1c7Bf8C071b33BD2ACa17e87dEF080FBf8636
   > block number:        90940
   > block timestamp:     1593430127
   > account:             0xC87392aFc75af828A577720c3BEE1088Ee5fa510
   > balance:             0
   > gas used:            505933 (0x7b84d)
   > gas price:           0 gwei
   > value sent:          0 ETH
   > total cost:          0 ETH
```
![image](https://user-images.githubusercontent.com/33336669/86000961-cee4dd00-ba40-11ea-99e8-d2f19a4a7332.png)

**Comment by caleteeter** [comment]
Thanks all, I have a fix that I was trying to push out this weekend, but I needed to change one of our tests to accommodate this gas change.  I feel good that this will be resolved today and the update will go out. `NOTE: This will be an extension update to v1.5.0`

On the telemetry on the portal, I noticed the same on my instances, I will surface this back to the ABS team.  I am confident the transactions are hitting the chain, and you can see this as well by reading the state of a contract back after an update.  The service is in public preview, so there might just be some issue with telemetry in these charts in the portal.

**Comment by ShockwaverReal** [comment]
After successfully deploying the contract I wanted to give it a try with "Show smart contract integration page" but I get the message "The current provider doesn't support subscriptions: y" and no contract actions can be selected... anyone?

**Comment by caleteeter** [comment]
@ShockwaverReal the current implementation of the smart contract interaction work for locally deployed contracts only, not for remote such as ABS.  We prioritized this for developers to test their contracts before deploying to remote nodes such as ABS or Infura.  Its in our backlog to enable this for remote networks.

**Comment by ShockwaverReal** [comment]
@caleteeter So, nothing to look under truffle-config.js, specifying a different provider for the network, right?

**Comment by ShockwaverReal** [comment]
For some reason I also got no interaction with a successful local deployment over ganache. Where should I look?

**Comment by caleteeter** [comment]
@ShockwaverReal correct, wondering are you using Retail or Insider VS Code?  I have an outstanding bug for this not rendering correctly with Insider, but Retail 1.46.1 should be fine.  Also, possible, delete your build folder and do a clean build/deploy local again.

**Comment by caleteeter** [comment]
I should fire up a gitter as the conversations are awesome here, but branching out in a few areas

**Comment by caleteeter** [comment]
https://gitter.im/blockchain-devkit/community <- more discussions here, I will be closing this issue when we release v1.5.0

**Comment by davew-msft** [comment]
Removing the gas line seems to work on both windows and ubuntu18.  Thanks @caleteeter .  I also have an old ABS instance from Feb and that wasn't experiencing the deployment issue...just tested that.  

One thing still not working is the "Show Smart Contracts Interaction Page" when on vscode on ubuntu/xfce4.  It does work on Windows.  Any thoughts on that?

**Comment by caleteeter** [comment]
v1.5.0 released with fix for the ABS gas bug.  @davew-msft, not a cop out but we haven't fully tested everything on Ubuntu, supported OS is Windows / Mac.  I will add this to the backlog as I do see in the telemetry that we have ubuntu users as well.

**Comment by davew-msft** [comment]
Understood.  Thank you sir.

**Comment by caleteeter** [comment]
Release completed, closing this.  Feel free to chat on gitter https://gitter.im/blockchain-devkit/community I will be there!

**Comment by davew-msft** [comment]
fwiw, I was deploying to abs this morning and forgot to remove the `gas` line and it worked!!!  Really, thanks for the help sir.
