### ISSUE TITLE
Contract not deployed yet warning. Contract address is allocated.

### ISSUE THREAD

**Issue by rykawagu** [microsoft/vscode-azure-blockchain-ethereum#59]
### environment
vscode-azure-blockchain-ethereum v1.5.0
VSCode: 1.47.2

### Symptom
When opening a smart contract via [Show smartcontract intraction page], it failed and the plugin warned contract not deployed yet.
deployed smart contract was newly added sol file to HelloBlockchain project, which is the auto-generated template.
Since contract addresses are all valid, this is extension issue.

### Repro Steps
(1) Select Blockchain > New Solidity Project (Basic)
(2) Add another sol file (example: another.sol) to the created project
(3) Add another deploy_contracts.js  (example: 3_deploy_contracts.js) for another.sol
(4) Build
(5) Deploy them to Azure Blockchain Service
(6) In log console, the plugin shows their contract addresses and accounts.
(7) When select another.sol and tried to debug by [Show Smartcontract intraction page], warning came up:

Screenshot:
![image](https://user-images.githubusercontent.com/42409300/87921367-6aec8c00-cab5-11ea-88ce-88aa951266c0.png)

**Comment by caleteeter** [comment]
@rykawagu unfortunately, there is no support for remote contracts with the Smart Contract Interaction component.  :(
