### ISSUE TITLE
Telemetry Client error - Get version for required apps

### ISSUE THREAD

**Issue by LucaGuida** [microsoft/vscode-azure-blockchain-ethereum#6]
When launching the extension I get the following error:

`[Telemetry Client] Initialize done with error: Instrumentation key not found, pass the key in the config to this method or set the key in the environment variable APPINSIGHTS_INSTRUMENTATIONKEY before starting the server
Get version for required apps`

Moreover, every time I try to execute command `Azure Blockchain: New Solidity Project` I get error `Get version for required apps`, but no further details about missing dependencies.

I have already installed all the required dependencies, as confirmed by the following output:

```
[Execute command] v10.15.3
[Execute command] 6.4.1
[Execute command] git version 2.21.0.windows.1
[Execute command] Python 2.7.15
[Execute command] Truffle v5.0.18 (core: 5.0.18)
[Execute command] Solidity v0.5.0 (solc-js)
[Execute command] Node v10.15.3
Web3.js v1.0.0-beta.37
[Execute command] Ganache CLI v6.4.3 (ganache-core: 2.5.5)
```

**Comment by caleteeter** [comment]
Hi @LucaGuida .  This list looks complete.  Can you ensure that your python binary is in your system path?  Also is this Windows or Mac?  What version os?

**Comment by LucaGuida** [comment]
I am running Visual Studio Code 1.34.0 on Windows 10 Enterprise (version 10.0.17763 Build 17763).
I have `C:\Python27` set in the "Path" system variable.

**Comment by caleteeter** [comment]
So the message in the output logs of `Get version for required apps` is not abnormal as this is a validation for required dependencies.  Just checking after you click on `Azure Blockchain: New Solidity Project` you should see this call in the output window and then you should get a prompt for `Create basic project` or `Create Project from truffle box`.  Basic will create a simple project.  Do you get an error if you select basic?

**Comment by LucaGuida** [comment]
In the meantime I uninstalled Visual Studio Editor, cleaned cache and temp files and performed a clean installation of VSE + Azure Blockchain extension. The issue seems to be fixed now. Thank you for your support!
