### ISSUE TITLE
Error running npx truffle unbox Azure-Samples/Blockchain-Ethereum-Template via VS Code

### ISSUE THREAD

**Issue by PingPongSet** [microsoft/vscode-azure-blockchain-ethereum#60]
I have the error below when creating a new project following the steps below:

https://docs.microsoft.com/en-gb/azure/blockchain/service/send-transaction

**Create a smart contract**

 1. From the VS Code command palette, choose Azure Blockchain: New
    Solidity Project.       
 2. Choose Create basic project.
 3. Create a new folder named HelloBlockchain and Select new project path.

>     Get version for required apps: node,npm,git
>     [Execute command]
>     Working dir: c:_MyLab\AzureCode\Blockchain\HelloBlockchain
>     Running command
>     npx truffle unbox Azure-Samples/Blockchain-Ethereum-Template
>     [Execute command]
>     Starting unbox...
>     [Execute command] =================
> 
>     [Execute command] - Preparing to download box
>     [Execute command] √ Preparing to download box
>     [Execute command] - Downloading
>     [Execute command] × Downloading
>     [Execute command] Unbox failed!
>     [Execute command] × Downloading
>     [Execute command] Unbox failed!
>     [Execute command] RequestError: Error: connect ETIMEDOUT 151.101.16.133:443
>     at new RequestError (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\errors.js:14:1)
>     at Request.plumbing.callback (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\plumbing.js:87:1)
>     at Request.RP$callback [as _callback] (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request-promise-core\lib\plumbing.js:46:1)
>     at self.callback (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:185:1)
>     at Request.emit (events.js:315:20)
>     at Request.onRequestError (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\node_modules\request\request.js:881:1)
>     at ClientRequest.emit (events.js:315:20)
>     at TLSSocket.socketErrorListener (_http_client.js:426:9)
>     at TLSSocket.emit (events.js:315:20)
>     at emitErrorNT (internal/streams/destroy.js:92:8)
>     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
>     [Execute command] Truffle v5.1.39 (core: 5.1.39)
>     [Execute command] Node v12.18.3
>     [Execute command] Finished running command

Same issue when I running the same command like below:

    C:\_MyLab\AzureCode\Blockchain\HelloBlockchain>npx truffle unbox Azure-Samples/Blockchain-Ethereum-Template

My Internet connection is working.

Sometimes, the error is 

> RequestError: Error: getaddrinfo ENOENT raw.githubusercontent.com

instead of 

> RequestError: Error: connect ETIMEDOUT 199.232.56.133:443

If download the app mannually, and run another command below, another error:

> Get version for required apps: truffle [Execute command]  Working dir:
> c:\_MyLab\AzureCode\Blockchain\HelloBlockchain Running command npx
> truffle compile [Execute command] Error: Cannot find module
> 'truffle-hdwallet-provider' Require stack:
> - c:\_MyLab\AzureCode\Blockchain\HelloBlockchain\truffle-config.js
> - C:\Users\username\AppData\Roaming\npm\node_modules\truffle\node_modules\original-require\index.js
> - C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:841:27)
>     at Module.require (internal/modules/cjs/loader.js:1025:19)
>     at require (internal/modules/cjs/helpers.js:72:18)
>     at Object.<anonymous> (c:\_MyLab\AzureCode\Blockchain\HelloBlockchain\truffle-config.js:1:26)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>     at Module.load (internal/modules/cjs/loader.js:985:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:878:14)
>     at Module.require (internal/modules/cjs/loader.js:1025:19)
>     at Object.require (internal/modules/cjs/helpers.js:72:18)
>     at Function.load (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\config\dist\index.js:161:1)
>     at Function.detect (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\config\dist\index.js:150:1)
>     at Object.run (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\commands\compile.js:68:1)
>     at Command.run (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\lib\command.js:136:1)
>     at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\core\cli.js:51:1)
>     at __webpack_require__ (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap:19:1)
>     at C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\webpack:\webpack\bootstrap:83:1
>     at Object.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:89:10)
>     at Module._compile (internal/modules/cjs/loader.js:1137:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
>     at Module.load (internal/modules/cjs/loader.js:985:32) [Execute command] Truffle v5.1.39 (core: 5.1.39) Node v12.18.3 [Execute
> command] Finished running command

**Comment by Wazzo79** [comment]
I'm also having issues creating a new Solidity project.

**Comment by caleteeter** [comment]
This new project model is pulling bits directly from github as you mentioned above.  I have just validated this and works fine here.  The github repo this is pulled from is here -> https://github.com/Azure-Samples/Blockchain-Ethereum-Template

Maybe some connection issue there?

**Comment by Wazzo79** [comment]
That was it, had to clear my npm cache and grant permissions to my global npm folders in order to properly install truffle and ganache

**Comment by caleteeter** [comment]
@PingPongSet feel free to open again, if you continue to have issue but appears to be connectivity and npm cache.

**Comment by PingPongSet** [comment]
@Wazzo79

> 
> 
> That was it, had to clear my npm cache and grant permissions to my global npm folders in order to properly install truffle and ganache

Please could you elaborate on how to clear npm cache and grant permissions?

**Comment by PingPongSet** [comment]
This is the first time I try to download Azure-Samples/Blockchain-Ethereum-Template via truffle, why is it to do with cache?

**Comment by PingPongSet** [comment]
I have tried quite a few different connections, where I can visit web pages, but I have this problem. What is required of connection that allows to download?
