### ISSUE TITLE
When installing truffle doesn't use the correct node binary.

### ISSUE THREAD

**Issue by krasi-georgiev** [microsoft/vscode-azure-blockchain-ethereum#62]
When trying to install `truffle` form the intro page link is fails.
Looking at the debug logs I see that it tries to install it with 
```
"/usr/bin/node" "/home/krasi/bin/npm/bin/npm" "i" "-g" "truffle@>=5.0.0 <6.0.0"
```
and it fails with 
```
390 error Error: EACCES: permission denied, access '/usr/lib'
```

For some reason there is another node binary in
```
$ which node
/home/krasi/.nvm/versions/node/v12.17.0/bin/node
```

I am not sure why the install script doesn't just use:

```
"node" "npm" "i" "-g" "truffle@>=5.0.0 <6.0.0"

```
and let the system resolve the correct paths.

This is kubuntu 20.04 LTS

full log attached

[2020-08-22T20_57_46_096Z-debug.log](https://github.com/microsoft/vscode-azure-blockchain-ethereum/files/5112991/2020-08-22T20_57_46_096Z-debug.log)

**Comment by caleteeter** [comment]
Sorry for the EXTREME lag on this @krasi-georgiev , we have some work to do with ubuntu, primarily targeted Mac and Windows for clients.
