### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by dhruvaop** [microsoft/vscode-azure-blockchain-ethereum#65]
- Issue Type: `Bug`
- Extension Name: `azure-blockchain`
- Extension Version: `1.5.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.50.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by caleteeter** [comment]
Sorry @dhruvaop , what is the bug you are reporting here?

**Comment by caleteeter** [comment]
No details, closing this issue.
