### ISSUE TITLE
VSCode plugin issue with Python

### ISSUE THREAD

**Issue by pinakighatak** [microsoft/vscode-azure-blockchain-ethereum#67]
Why does this plugin not respect the fact I have an updated version of Python installed (3.9) and keeps insisting on 2.7.15 specifically?
![image](https://user-images.githubusercontent.com/57876192/97431577-76e8b500-1912-11eb-9340-0783977e926b.png)

**Comment by caleteeter** [comment]
@pinakighatak we have just released v1.6 that removes the need for Python from the extension.  This has been a long time coming.  There was a dependency on this a component that we use, so a bit complex to get this changed.
