### ISSUE TITLE
[Execute command] 'python' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Sshetty2** [microsoft/vscode-azure-blockchain-ethereum#7]
Trying to see why my version of Python is not found.. I am running WSL and the integrated terminal is set up to run bash but I have python installed on windows and linux and python is configured the environment variables for both environments should be configured correctly. If I run 'python' from the command line, I will be able to enter the REPL with no issues from bash or powershell. 

I'm not sure why the azure blockchain toolkit won't recognize my installed python. 

Please advise

**Comment by caleteeter** [comment]
Ok, so you have Python installed on Windows which is the core requirement.  In the setup of the installer for Python for Windows (should be 2.7.x) there is an option to add Python to the system path.  If this was not done at installation, no worries you can open Settings -> search for Environment Variables and click on `Edit the system environment variables`.  Click on the button `Environment Variables`, then in the lower box find Path, click Edit and add the path to the Python install (typical location is C:\Python27.

**Comment by caleteeter** [comment]
Hi @Sshetty2, pinging back to see if you were still having issues here?

**Comment by Sshetty2** [comment]
Hello, you can close this one

Thanks
------------------------------------------------------------------------------------------------

If you're a Meetup.com User, check out this Chrome extension I developed
to help you batch schedule Meetup.com events to your Google Calendar  :

https://chrome.google.com/webstore/detail/meetup-batch-event-set-to/cabfodbfjmgloaallchcnnkgcfpnobem
