### ISSUE TITLE
Unable to use Development Kit in VS Code

### ISSUE THREAD

**Issue by tdegruijter** [microsoft/vscode-azure-blockchain-ethereum#75]
when I install the Blockchain Development Kit for Ethereum for VS Code, I try to use the command palette with the command 'Blockchain: Show Welcome Page'. The error text is: "Command 'Blockchain: Show Welcome Page' resulted in an error (command 'azureBlockchainService.showWelcomePage' not found)"

I also try to use the command 'Blockchain: New Solidity Project'. The error text is: "Command 'Blockchain: New Solidity Project' resulted in an error (command 'truffle.newSolidityProject' not found)"

here is what i am running:

Python 3.9.5
VS Code Version 1.56.2 (user setup)
Ganache CLI v6.12.2 (ganache-core: 2.13.2)
Truffle v5.3.7 - a development framework for Ethereum
Node.js - v14.17.0
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042

Other error messages: 
[Azure Blockchain] Cannot read property 'uri' of undefined

I have uninstalled and re-installed every single component (vs code, ganache, truffle, and node.js + npm) multiple times. I don't understand what I'm doing wrong.  This is very frustrating. Please help

**Comment by caleteeter** [comment]
Turns out we had an bug come in between some changes made in Truffle that affected the extension.  This is being resolved in the next release of Truffle.  In the meantime, you can install truffle version 5.3.10 which will work.

```
npm uninstall -g truffle
npm i -g truffle@5.3.10
```

Sorry about that!  :)

**Comment by caleteeter** [comment]
Truffle has released an update that addresses this (https://github.com/trufflesuite/truffle/releases/tag/v5.3.13).

```
npm uninstall -g truffle
npm i -g truffle
```
