### ISSUE TITLE
Cannot create a Basic Project using VS Code extension

### ISSUE THREAD

**Issue by pjjohnson** [microsoft/vscode-azure-blockchain-ethereum#9]
node 10.15.3
git 2.22.0.windows.1
python 2.7.15
npm 6.9.0
Windows build 10.0.18362.175
VS Code 1.35.1

When I created a Basic Project via the VS Code extension, it would fail with deprecation errors; however, I could connect to my consortium without any issues.

After talking with MS experts, it was recommended I install the the Windows Global Build tools via the command "npm install --global windows-build-tools" which I ran in an elevated PowerShell session.  I did run into an initial problem with this install, and I had to delete the folder "...\AppData\Roaming\npm\node_modules\windows-build-tools" - this was likely due to processes that we're still active.  Once I rebooted and reran the install, everything worked perfectly.

**Comment by caleteeter** [comment]
Thanks @pjjohnson .  We have this in the active backlog and working on a fix to remove the need to do this manual package install.

**Comment by caleteeter** [comment]
I have updated the Wiki [entry](https://github.com/microsoft/vscode-azure-blockchain-ethereum/wiki/FAQ#Q-i-am-using-the-extension-to-create-a-new-solidity-project-and-i-am-getting-errors-when-creating-the-project) to provide the resolution.  We are continuing to look at removing this step for new installs but need to work with dependent libraries to correct.  Closing the issue for now.
